export default {
  /**
   * MAIN ENTRY FILES (SCSS | JS)
   */
  JS_ENTRIES: ["main.js"], // Main JS file to import / require from
  SCSS_ENTRIES: ["main.scss"], // Main scss file to import / require from

  /**
   * PROXY CONFIGURATION
   * */
  PROXY_TARGET: "https://valisette.app", // The URL that broadcasts your app on your machine which is the name of the root `https://${base_folder}.app` by default

  /**
   * DEV SERVER CONFIGURATION
   */
  DEV_SERVER_PORT: 1337,

  /**
   * DEVTOOLS
   * */
  VERBOSE: false, // Allows compiler to log debug messages during build
  DESKTOP_NOTIFICATIONS: true, // Allow compiler to notify you from the desktop when it's done
  IGNORE_WARNINGS: false, // ignore warnings log messages

  /**
   * BUILD FEATURES
   * */
  PWA_MODE: true, // Turn your app into a Progressive Web App
  OFFLINE_MODE: true, // Loads your assets in a service worker to enable PWA features
  GENERATE_HTML: true, // Make compiler generate an index.html file in public folder
  EXTRACT_CSS: true, // Extract css/scss from vuejs components
  COMPRESSION_TRESHOLD: 10240, // Treshold in bytes from which you bundles will be compressed if they are above this size
  PROD_APP_MAX_SIZE_WARNING : 380000, // entry points max size that will trigger a flag in build stats
  PROD_PACKAGES_MAX_SIZE: 150000, // max size you want your modules to be split into (if file can be split) in production
  DEV_APP_MAX_SIZE_WARNING : 1500000000, // entry points max size that will trigger a flag in build stats
  DEV_PACKAGES_MAX_SIZE: 1500000000, // max size you want your modules to be split into (if file can be split) in development

  /**
   * VUE JS
   * */
  VUE_RUNTIME: false, // Use vue template inside html files (true) or render app on a mount point (false)

  /**
   * PERFORMANCE
   * */
  AUDIT: false, // enable bundle analyzer to audit your code
  PERFORMANCE_LOG_LEVEL: "warning", // set performance hints log importance level

  /**
   * FILE SYSTEM
   * */
  ASSETS_PATH: "resources/assets/", // source assets files location
  ASSETS_PUBLIC_PATH: "/",
  PUBLIC_PATH: "/public/", // Public assets folder path
  PUBLIC_MANIFEST_PATH: "/", // Public assets manifest location
  JS_PATH: "javascript/", // Javascript folder name
  TS_PATH: "typescript/", // Typescript folder name
  CSS_PATH: "css/", // Css folder name
  IMAGES_PATH: "images/", // Images folder name
  FONTS_PATH: "fonts/", // Fonts folder name
  SCSS_PATH: "scss/", // scss source folder
  HARD_CLEANUP: false,

  /**
   * OUTPUT NAMES
   * */
  JS_MAIN_OUTPUT: "[name].js", // js file output name pattern
  JS_CHUNK_OUTPUT: "[name]-[contenthash].chunk.js", // code chunks files generated by code splitting name pattern (don't edit /*.chunk.*/ pattern)
  CSS_MAIN_OUTPUT: "[name].css", // css file output name pattern (used in production mode)
  CSS_CHUNK_OUTPUT: "[name]-[contenthash].chunk.css", // code chunks files generated by code splitting name pattern (don't edit /*.chunk.*/ pattern)

  /**
   * PWA MANIFEST
   * */
  APP_URL: "https://valisette.app", // app url to specify for service workers
  APP_NAME: "Valisette by 16 Pixels", // PWA public name
  SHORT_APP_NAME: "Valisette", // PWA public shot name
  APP_DESCRIPTION:
    "Valisette :  : a boilerplate for valet & vue users by 16 Pixels. https://github.com/16pixels", // PWA public description
  BACKGROUND_COLOR: "#3a74a5",  // PWA Main color
  THEME_COLOR: "#3a74a5", // PWA Theme color
  APP_LOGO: "./public/valisette-logo.png", // PWA public logo

  /**
   * HTML GENERATION
   */
  HTML_TEMPLATE: "index.ejs", // Template from which to generate your html
  HTML_OUTPUT_NAME: "index.html" // Name that will be given to output html file
};
